name: Test Automation Workflow

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Run tests
      run: mvn test -X -Dbrowser=chrome -DisHeadless=true

    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
          name: Test logs
          path: logs/

    - name: Upload extentReport report
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
          name: ExtentReport report
          path: extentReport.html

    - name: Test execution status
      run: echo "Test execution complete"

    - name: Copy pages to gh-pages
      if: always()

      run: |
          mkdir -p public/extent-reports
          cp -R extentReport.html public/extent-reports/
          ls -l

    - name: Deploy to GitHub Pages
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
          folder: public/extent-reports
          token: ${{ secrets.ACCESSTOKENTEST }}
          clean: true

    


