name: Test Automation Workflow

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Run tests
      run: mvn test -X -Dbrowser=chrome -DisHeadless=true

    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
          name: Test logs
          path: logs/

    - name: Upload test reort
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
          name: Test report
          path: report.html

    - name: Upload extendReport logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
          name: extendReport logs
          path: /extendReport.html

    - name: Test execution status
      run: echo "Test execution complete"


